language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r ./Source/Python/python_sort/requirements-dev.txt"

# command to run tests
script: cd Source/Python/python_sort && paver test_all
